//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mah_Noor_S00199547Final_Exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameInfo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Platform { get; set; }
        public string CriticsScore { get; set; }
        public string Price { get; set; }
        public string GaneImage { get; set; }
        public string Decsription { get; set; }
    }
}
